### ISSUE TITLE
When creating an item it is not clear which forms you need to fill to be able to save

### ISSUE THREAD

**Issue by djtanuzzo** [merkatsu/website#89] opened 2015-04-16 12:13 UTC
When you create a new item it is not clear which forms you need to fill to be able to save it. The text only says how many you are missing, but now which ones.

![mrkts1](https://cloud.githubusercontent.com/assets/10848233/7180526/43b7d926-e43a-11e4-8339-98cc449caa7e.png)

**Comment by djtanuzzo** [comment] 2015-04-17 13:20
Having checked the issue after it was closed I didn't notice a difference. @PedroEsperanca said that the colors are different for the forms that you still need to fill. Personally I didn't find this to be enough, and would prefer a clear text saying which forms still need to be filled. Maybe @mariacovasgrilo should pitch in and give her opinion on the discussion.

**Comment by mariacovasgrilo** [comment] 2015-04-19 19:58
Maybe having a small icon in front of the field that needs to be filled would be good.

But I wonder if it wouldn't be more educative for the user to actually click "save" just to find out that he still misses things? Because then when he would click save, the fields that were still missing would blink and change color. 

Now, having the color change immediately once you decide to skip one field and fill in the next one, doesn't help me learn what the problem is, later, when I want to save.

**Comment by esperancaJS** [comment] 2015-04-19 20:18
I like the 'blinking' idea

But I think that required fields need to be marked as such all the time they are invalid/empty. Honestly I think the highlight color (as it is now) plus the blinking will work perfectly.

I also had planned on adding the required fields names bellow: `please complete the form, x left`

another small note: the `x left` is now in highlighted color

![Image of Yaktocat](https://lh5.googleusercontent.com/IUa6m2PyiqovndxvGmHvpLWu1vTqSqpFDivjEaTHW9dOacS45Aqk8-CqkudbMRJa29Fd3GCKIAaOT60=w1884-h715)

**Comment by djtanuzzo** [comment] 2015-04-20 09:22
The problem I can see with the blinking and color changing is that they can easily be missed or misunderstood, especially if you are missing different fields in different parts that are out of view. Also what about colorblind people?

I think that the best solution would be to:
- Write in the form
- Click save
- Get a text saying "you still need to complete the following:" and then it explicitly says what you are missing

**Comment by mariacovasgrilo** [comment] 2015-04-20 09:40
sounds good to me @djtanuzzo

**Closed as completed** 2015-09-19 23:59 UTC
Labels: enhancement, UX
